// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYsFxOarPeL8tI9wKRZUG1i5nWHsdOtAI',
    appId: '1:293260843628:web:9eb444e416830022105649',
    messagingSenderId: '293260843628',
    projectId: 'tatoo-reservation-app',
    authDomain: 'tatoo-reservation-app.firebaseapp.com',
    storageBucket: 'tatoo-reservation-app.appspot.com', // ✅ 수정됨
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVOF5bIkn72iq-JO7mCZf_rS3PNfvyr8E',
    appId: '1:293260843628:android:bd815b80205a8757105649',
    messagingSenderId: '293260843628',
    projectId: 'tatoo-reservation-app',
    storageBucket: 'tatoo-reservation-app.appspot.com', // ✅ 수정됨
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5Ua6W9zMlMWPTeON9KaaE68q0D-KRDc',
    appId: '1:293260843628:ios:8c6dc23e34871ceb105649',
    messagingSenderId: '293260843628',
    projectId: 'tatoo-reservation-app',
    storageBucket: 'tatoo-reservation-app.appspot.com', // ✅ 수정됨
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq5Ua6W9zMlMWPTeON9KaaE68q0D-KRDc',
    appId: '1:293260843628:ios:8c6dc23e34871ceb105649',
    messagingSenderId: '293260843628',
    projectId: 'tatoo-reservation-app',
    storageBucket: 'tatoo-reservation-app.appspot.com', // ✅ 수정됨
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYsFxOarPeL8tI9wKRZUG1i5nWHsdOtAI',
    appId: '1:293260843628:web:3a98f3e189a697f8105649',
    messagingSenderId: '293260843628',
    projectId: 'tatoo-reservation-app',
    authDomain: 'tatoo-reservation-app.firebaseapp.com',
    storageBucket: 'tatoo-reservation-app.appspot.com', // ✅ 수정됨
  );
} //FIREBASE_OPTIONS.DART
